apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dominoes-game
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project
  project: default

  # Source
  source:
    repoURL: https://github.com/ArsalanAnwer0/Dominoes-Game.git  # Change to your repo
    targetRevision: main
    path: helm/dominoes-game
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: latest  # This will be updated by CI/CD

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync Policy
  syncPolicy:
    automated:
      prune: true      # Delete resources when removed from Git
      selfHeal: true   # Auto-sync when cluster state differs
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replicas