version: '3.8'

services:
  dominoes-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dominoes-game
    ports:
      - "8081:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    labels:
      - "com.dominoes.app=game"
      - "com.dominoes.environment=local"